create table if not exists public.client_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  level text not null default 'error',
  source text not null,
  message text not null,
  page_url text,
  user_agent text,
  username text,
  user_email text,
  user_id uuid,
  session_id text,
  app_version text,
  details jsonb not null default '{}'::jsonb
);

create index if not exists client_logs_created_at_idx
on public.client_logs (created_at desc);

create index if not exists client_logs_source_idx
on public.client_logs (source);

create index if not exists client_logs_user_id_idx
on public.client_logs (user_id, created_at desc);

alter table public.client_logs enable row level security;

grant insert on public.client_logs to authenticated;
grant usage, select on sequence public.client_logs_id_seq to authenticated;

drop policy if exists app_insert_client_logs_authenticated on public.client_logs;

create policy app_insert_client_logs_authenticated
on public.client_logs
for insert
to authenticated
with check (
  auth.uid() = user_id
  and coalesce(nullif(trim(user_email), ''), lower(coalesce(auth.jwt() ->> 'email', ''))) = lower(coalesce(auth.jwt() ->> 'email', ''))
);
