begin;

create table if not exists public.sevkiyatlar (
  id bigint generated by default as identity primary key,
  tarih date not null,
  kullanici text not null,
  yogurt3kg numeric(12,2) not null default 0,
  yogurt5kg numeric(12,2) not null default 0,
  kaymak numeric(12,2) not null default 0,
  ekleyen text not null default lower(coalesce(auth.jwt() ->> 'email', '')),
  created_by uuid not null default auth.uid(),
  created_at timestamptz not null default now()
);

create index if not exists sevkiyatlar_tarih_idx
on public.sevkiyatlar (tarih desc, created_at desc);

create index if not exists sevkiyatlar_kullanici_idx
on public.sevkiyatlar (lower(kullanici));

alter table public.sevkiyatlar enable row level security;

grant select, insert, update, delete on public.sevkiyatlar to authenticated;
grant usage, select on sequence public.sevkiyatlar_id_seq to authenticated;

drop policy if exists app_select_authenticated on public.sevkiyatlar;
drop policy if exists app_insert_owner_only on public.sevkiyatlar;
drop policy if exists app_update_owner_or_admin on public.sevkiyatlar;
drop policy if exists app_delete_owner_or_admin on public.sevkiyatlar;

create policy app_select_authenticated
on public.sevkiyatlar
for select
to authenticated
using (true);

create policy app_insert_owner_only
on public.sevkiyatlar
for insert
to authenticated
with check (
  auth.uid() = created_by
  and public.matches_requester_email(ekleyen)
);

create policy app_update_owner_or_admin
on public.sevkiyatlar
for update
to authenticated
using (public.can_manage_owned_record(created_by, ekleyen))
with check (
  public.can_manage_owned_record(created_by, ekleyen)
  and (auth.uid() = created_by or public.is_admin_email())
);

create policy app_delete_owner_or_admin
on public.sevkiyatlar
for delete
to authenticated
using (public.can_manage_owned_record(created_by, ekleyen));

commit;
